### ISSUE TITLE
getting blank folders

### ISSUE THREAD

**Issue by YaoyangWU** [Sublunarwind/keyword_based_Sina_weibo_crawler#1]
Hi :) I am totally new on this please bear with me..
So I am trying to run this nice little crawler on python3 when I found that I am only getting blank folders named with the date, but nothing in it, and the process stuck at printing out the sentence "Log output finished". mylog.txt is nice and recorded, would you be so kind to tell me what is wrong? Thank you so much.
P.S. Also I got the exception message "Get this endtime fail", how should I change the JSON stucture?

**Comment by Sublunarwind** [comment]
I have updated a Python3.5 version, it's in the folder.
The errors related are listed below, mainly caused by the different grammar between 2 and 3>

**Python: Importing urllib.quote error**
[stackoverflow](https://stackoverflow.com/questions/31827012/python-importing-urllib-quote)

**the JSON object must be str, not 'dict' error**
[stackoverflow](https://stackoverflow.com/questions/36804132/why-wont-python3-load-this-json-string)

**write() argument must be str, not bytes error**
[stackoverflow](https://stackoverflow.com/questions/38524770/write-argument-must-be-str-not-bytes)

**'str' object has no attribute 'decode'. Python 3 error**
[stackoverflow](https://stackoverflow.com/questions/28583565/str-object-has-no-attribute-decode-python-3-error)

**Comment by YaoyangWU** [comment]
Works like a charm :D Thank you
